
base_url = "http://magentofinal.mytriorings.com/"

url_for_test = [
    'about',
    # 'services',
    # 'layaway-plan',
    # 'fake_path',
    # '30-day-satisfaction-guarantee',
    # 'bridal-rings',
    # 'buy-now-pay-later',
    # 'buying-online',
    # 'carat-weight-tolerance',
    # 'contact-us',
    # 'customer-service',
    # 'customer-spotlight',
    # 'diamond-overview',
    # 'diamond-trends',
    # 'education',
    # 'engagement-rings',
    # 'for-the-perfect-match',
    # 'free-shipping',
    # 'full-brilliance-collection',
    # 'gold-overview',
    # 'ladies-wedding-bands',
    # 'mens-wedding-bands',
    # 'military',
    # 'my-trio-rings-in-the-media',
    # 'platinum-jewlery',
    # 'plus-size-wedding-ring-sets',
    # 'requesting-an-ma',
    # 'revelinrose',
    # 'ring-fit-types',
    # 'ring-size-guide',
    # 'same-sex-wedding-bands',
    # 'she-said-yes-special',
    # 'stackable-trio',
    # 'student',
    # 'the-4cs',
    # 'todays-diamond-industry',
    # 'tri-rings',
    # 'understanding-diamond-indusrty',
    # 'us-vs-them',
    # 'warranty-and-repairs',
    # 'ways-to-pay',
    # 'wedding-ring-sets-on-a-budget',
    # 'what-is-a-trio-wedding-ring-set',
    # 'worry-free-shopping'
]
